### ISSUE TITLE
What does distill mappings dict do?

### ISSUE THREAD

**Issue by raypretam** [amazon-science/dq-bart#2]
Could you tell why are you using  distill_mappings dict used in run_summarization_no_trainer.py file like follows?

```
distill_mappings = {1: {0: 5},
                    2: {0: 0, 1: 5},
                    3: {0: 0, 1: 2, 2: 5},
                    4: {0: 0, 1: 2, 2: 3, 3: 5},
                    5: {0: 0, 1: 1, 2: 3, 3: 4, 4: 5},
                    6: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
                    }
```
And what is the meaning of this parameter in configuration_bart_quant.py file ```decoder_start_token_id=2```?

**Comment by zijwang** [comment]
`distill_mappings` controls which layer is distilled from which layer. 
`decoder_start_token_id` see https://github.com/huggingface/transformers/blob/main/src/transformers/models/bart/configuration_bart.py#L140
