### ISSUE TITLE
Model Compression Questions

### ISSUE THREAD

**Issue by sanchit-gandhi** [amazon-science/dq-bart#6]
Hey @zijwang,

Congrats on the DQ-BART paper and thanks so much for open-sourcing this repo 🤗 It's great reference material for future distillation + quantisation endeavours!

I had a few of questions about model compression:
1. **How is the compressed model size calculated?** We quantise the model by rounding the weights according to symmetric linear quantisation:
https://github.com/amazon-science/dq-bart/blob/378683e2af63b70affc490b764b98d2997fd51ac/quant/utils_quant.py#L18
Or ternarization:
https://github.com/amazon-science/dq-bart/blob/378683e2af63b70affc490b764b98d2997fd51ac/quant/utils_quant.py#L124
This rounds the weights to 8-bits or 2-bits respectively. However, the weights are still stored in float32 (or float16 if we initialise the model in half-precision), so the overall model size is un-changed right? How do we realise the model compression on the dtype level (do we need to convert to int8 here)? My question is: we round the weights to 8-bit, but still store them in float32, so where does the 'model compression' come from?
2. **Is there separate code for inference?** From the code, we compute the quantised weights _on the fly_ in the forward pass for each layer:
https://github.com/amazon-science/dq-bart/blob/378683e2af63b70affc490b764b98d2997fd51ac/quant/utils_quant.py#L188-L190
This way we keep a copy of the full-precision weights (`self.weights`) and the quantised weights (`weights`) during training. For inference, we only need the quantised weights. Since these weights are fixed at inference time, my guess is that we only do this quantisation once in the `__init__`, and then re-use the quantised layers for each `.forward()` call? Something along the lines of:
```python
class QuantizeLinear(nn.Linear):
    def __init__(...):
        ...
        # quantize weight once for inference
        self.weight = nn.parameter.Parameter(self.weight_quantizer.apply(self.weight, self.weight_clip_val, self.weight_bits, True))
```
3. **Are there reference numbers for _inference speed_?** Based on my benchmarks, running in 2 or 8-bit precision takes up to 6x longer than native fp16 (with the inference code changes outlined above). Is this similar to what you found with your DQ-BART experiments? The paper only quotes model compression ratios!
4. **Are any of the DQ-BART models checkpoints available for download?** Even as raw `pytorch_model.bin` files it would be super cool to benchmark them for inference (and properly understand the above three questions!)

Thanks so much for your time! Happy to clarify any of the questions!

**Comment by zijwang** [comment]
Hi @sanchit-gandhi 
Thanks for your interest in our work!
re model size: following previous work (TernaryBERT), we calculate the model size based on the quantized bits (2-bit is 1/4 of 8-bit). 
re inference speed: As you mentioned too, inference speed with low-bit quantization heavily depends on the hardware and specific optimizations/kernels on top of the hardware, which is beyond the focus of this work. 
re checkpoint: we didn't release the checkpoint but [the command in the readme](https://github.com/amazon-science/dq-bart#sample-command) should reproduce the result in the paper.

**Comment by sanchit-gandhi** [comment]
Hey @zijwang! Thank you so much for your reply - the clarifications are most helpful! 

Regarding the quantised weights, they are still stored in float32 in the code (or float16 if we initialise the model in half-precision). How do we realise the model compression on the `dtype` level? Is there a conversion that is performed to convert the `dtype` of the weights down to 2-bit/8-bit?

**Comment by zijwang** [comment]
Yes, this is done so no custom dtype is required through training. You can define custom dtype and store 2/8 bit there to realize the compression ratio when deployed.
