### ISSUE TITLE
Inference speed of DQ-Bart

### ISSUE THREAD

**Issue by sinking-point** [amazon-science/dq-bart#7]
Hi team,

Great work and thanks for your contributions. The footprint reductions alone make this project important. 

Do you have any data on the inference speed of these models Vs original Bart?

**Comment by zijwang** [comment]
Hi @sinking-point ! Thanks for your interest! As also mentioned in https://github.com/amazon-science/dq-bart/issues/6#issuecomment-1475469688 , we don't have inference speed benchmarking as it depends on many other factors that are beyond the scope of the work.

**Comment by sinking-point** [comment]
Okay, fair enough. Thanks for your reply.
